### ISSUE TITLE
ApexDoc crashes since rel/3.111

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/NPSP#2822]
ApexDoc crashes for tag rel/3.111. It worked fine for rel/3.110. ApexDoc itself hasn't changed in that time. Here is the Java command and stack trace:

```bash
Cumulus $ java -jar ~/Downloads/apexdoc.jar -s src/classes -t . -g https://github.com/SalesforceFoundation/Cumulus/blob/rel/3.111/src/classes/ -h ApexDocContent/homepage.htm -a ApexDocContent/projectheader.htm -p "global;public;private;testmethod;webService"

java.lang.NullPointerException
	at org.salesforce.apexdoc.ClassModel$1.compare(Unknown Source)
	at org.salesforce.apexdoc.ClassModel$1.compare(Unknown Source)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.salesforce.apexdoc.ClassModel.getMethodsSorted(Unknown Source)
	at org.salesforce.apexdoc.FileManager.htmlForClassModel(Unknown Source)
	at org.salesforce.apexdoc.FileManager.makeFile(Unknown Source)
	at org.salesforce.apexdoc.FileManager.createDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.main(Unknown Source)
```

**Comment by judisohn** [comment]
**lurch: add

**Comment by mbeaty-sf** [comment]
Salesforce has determined that this issue will not be explored further.
