### ISSUE TITLE
Gift Entry new batch component errors

### ISSUE THREAD

**Issue by davidchengIC** [SalesforceFoundation/NPSP#5418]
Using the new Gift Entry.  When I try to create a new Batch, I get two component errors after I click Save on the default values screen.  I've checked all the class and field permissions and I think I get them all right.

First error:
A component error has occurred

[NoErrorObjectAvailable] Script error.

Component descriptor
markup://npsp:geFormRenderer

Filename
https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js

line 936 column 169

function a

stacktrace
a()@https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:936:169
{anonymous}()@https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:936:362
Z.dispatchEvent()@https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:25839
Z.value [as dispatchEvent]()@https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:29:34217
Z.initializeForm()@https://amacad--partial.lightning.force.com/lightning/n/modules/npsp/geFormRenderer.js:4:8792
eval()@https://amacad--partial.lightning.force.com/lightning/n/modules/npsp/geFormRenderer.js:4:9314

When I close this popup, there's a second one underneath:

A component error has occurred

Cannot read property 'Target_Field_Data_Type' of undefined

npsp:GE_GiftEntryForm

TypeError: Cannot read property 'Target_Field_Data_Type' of undefined
    at A.get fieldType [as fieldType] (https://amacad--partial.lightning.force.com/lightning/n/modules/npsp/geFormField.js:4:6613)
    at A.get isLightningInput [as isLightningInput] (https://amacad--partial.lightning.force.com/lightning/n/modules/npsp/geFormField.js:4:6707)
    at m (https://amacad--partial.lightning.force.com/lightning/n/modules/npsp/geFormField.js:4:146)
    at https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:23536
    at Ne.observe (https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:10659)
    at ao (https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:22810)
    at Ir (https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:34283)
    at fo (https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:22717)
    at https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:24647
    at wo (https://static.lightning.force.com/cs37/auraFW/javascript/kHqYrsGCjDhXliyGcYtIfA/aura_prod.js:4:24658)
![Screen Shot 2020-05-05 at 1 44 52 PM](https://user-images.githubusercontent.com/17989412/81116200-cc9b5200-8ed9-11ea-9d08-75e091627da5.png)
![Screen Shot 2020-05-05 at 1 43 46 PM](https://user-images.githubusercontent.com/17989412/81116204-cdcc7f00-8ed9-11ea-8b41-0f953bfb6b17.png)

**Comment by davidchengIC** [comment]
Hub post:  https://powerofus.force.com/s/feed/0D51E00005B5c3ESAR

**Comment by davidchengIC** [comment]
Note - this occurs when selecting a custom template or the default template (which I did not change).

**Comment by mbeaty-sf** [comment]
Closing this so that the conversation can continue on the Hub thread.
